"use strict";this.default_IdentityRotateCookiesHttp=this.default_IdentityRotateCookiesHttp||{};(function(_){var window=this;
try{
_._F_toggles_initialize=function(a){("undefined"!==typeof globalThis?globalThis:"undefined"!==typeof self?self:this)._F_toggles=a||[]};(0,_._F_toggles_initialize)([0x306, ]);
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var q=function(a){return aa?p?p.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1},t=function(a){var b;a:{if(b=r.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)},u=function(){return aa?!!p&&0<p.brands.length:!1},v=function(){return u()?q("Chromium"):(t("Chrome")||t("CriOS"))&&!(u()?0:t("Edge"))||t("Silk")},x=function(){return"function"===typeof BigInt},C=function(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);b&&(c=y(z(c,a)),b=c.next().value,
a=c.next().value,c=b);A=c>>>0;B=a>>>0},ca=function(a,b){b>>>=0;a>>>=0;if(2097151>=b)var c=""+(4294967296*b+a);else x()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+6777216*c+6710656*b,c+=8147497*b,b*=2,1E7<=a&&(c+=Math.floor(a/1E7),a%=1E7),1E7<=c&&(b+=Math.floor(c/1E7),c%=1E7),c=b+ba(c)+ba(a));return c},ba=function(a){a=String(a);return"0000000".slice(a.length)+a},da=function(){var a=A,b=B;b&2147483648?x()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):
(b=y(z(a,b)),a=b.next().value,b=b.next().value,a="-"+ca(a,b)):a=ca(a,b);return a},z=function(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]},ea=function(a){a=a>>14&1023;return 0===a?536870912:a},ha=function(a){return!(!a||"object"!==typeof a||a.g!==fa)},E=function(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object},H=function(a,b,c){if(!Array.isArray(a)||a.length)return!1;var e=F(a);if(e&1)return!0;if(!(b&&(Array.isArray(b)?b.includes(c):b.has(c))))return!1;G(a,e|1);return!0},
I=function(a){a=Error(a);a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity="warning";return a},ja=function(a){var b=typeof a;return"number"===b?Number.isFinite(a):"string"!==b?!1:ia.test(a)},ka=function(a){return"-"===a[0]?20>a.length?!0:20===a.length&&-922337<Number(a.substring(0,7)):19>a.length?!0:19===a.length&&922337>Number(a.substring(0,6))},la=function(a){a=Math.trunc(a);if(!Number.isSafeInteger(a)){C(a);var b=A,c=B;if(a=
c&2147483648)b=~b+1>>>0,c=~c>>>0,0==b&&(c=c+1>>>0);b=4294967296*c+(b>>>0);a=a?-b:b}return a},ma=function(a){var b=Math.trunc(Number(a));if(Number.isSafeInteger(b))return String(b);b=a.indexOf(".");-1!==b&&(a=a.substring(0,b));if(!ka(a)){if(16>a.length)C(Number(a));else if(x())a=BigInt(a),A=Number(a&BigInt(4294967295))>>>0,B=Number(a>>BigInt(32)&BigInt(4294967295));else{b=+("-"===a[0]);B=A=0;for(var c=a.length,e=b,f=(c-b)%6+b;f<=c;e=f,f+=6)e=Number(a.slice(e,f)),B*=1E6,A=1E6*A+e,4294967296<=A&&(B+=
Math.trunc(A/4294967296),B>>>=0,A>>>=0);b&&(b=y(z(A,B)),a=b.next().value,b=b.next().value,A=a,B=b)}a=da()}return a},K=function(a,b,c){null==a&&(a=J);J=void 0;if(null==a){var e=96;c?(a=[c],e|=512):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("i");e=F(a);if(e&2048)throw Error("j");if(e&64)return a;e|=64;if(c&&(e|=512,c!==a[0]))throw Error("k");a:{c=a;var f=c.length;if(f){var k=f-1;if(E(c[k])){e|=256;b=k-(+!!(e&512)-1);if(1024<=b)throw Error("l");e=e&-16760833|(b&1023)<<
14;break a}}if(b){b=Math.max(b,f-(+!!(e&512)-1));if(1024<b)throw Error("m");e=e&-16760833|(b&1023)<<14}}}G(a,e);return a},oa=function(a,b){return na(b)},na=function(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a)if(Array.isArray(a)){if(H(a,void 0,0))return}else if(pa&&null!=a&&a instanceof Uint8Array){if(qa){for(var b="",c=0,e=a.length-10240;c<e;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,
c?a.subarray(c):a);a=btoa(b)}else{void 0===b&&(b=0);if(!L){L={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");e=["+/=","+/","-_=","-_.","-_"];for(var f=0;5>f;f++){var k=c.concat(e[f].split(""));ra[f]=k;for(var d=0;d<k.length;d++){var g=k[d];void 0===L[g]&&(L[g]=d)}}}b=ra[b];c=Array(Math.floor(a.length/3));e=b[64]||"";for(f=k=0;k<a.length-2;k+=3){var h=a[k],l=a[k+1];g=a[k+2];d=b[h>>2];h=b[(h&3)<<4|l>>4];l=b[(l&15)<<2|g>>6];g=b[g&63];c[f++]=d+h+l+g}d=0;g=e;switch(a.length-
k){case 2:d=a[k+1],g=b[(d&15)<<2]||e;case 1:a=a[k],c[f]=b[a>>2]+b[(a&3)<<4|d>>4]+g+e}a=c.join("")}return a}}return a},ta=function(a,b,c,e,f){if(null!=a){if(Array.isArray(a))a=H(a,void 0,0)?void 0:f&&F(a)&2?a:sa(a,b,c,void 0!==e,f);else if(E(a)){var k={},d;for(d in a)k[d]=ta(a[d],b,c,e,f);a=k}else a=b(a,e);return a}},sa=function(a,b,c,e,f){var k=e||c?F(a):0;e=e?!!(k&32):void 0;a=Array.prototype.slice.call(a);for(var d=0;d<a.length;d++)a[d]=ta(a[d],b,c,e,f);c&&c(k,a);return a},va=function(a){return a.G===
ua?a.toJSON():na(a)},N=function(a,b,c){var e=wa?void 0:a.constructor.J;var f=M(c?a.j:b);a=b.length;if(!a)return b;var k;if(E(c=b[a-1])){a:{var d=c;var g={},h=!1,l;for(l in d){var m=d[l];if(Array.isArray(m)){var D=m;if(H(m,e,+l)||ha(m)&&0===m.size)m=null;m!=D&&(h=!0)}null!=m?g[l]=m:h=!0}if(h){for(var n in g){d=g;break a}d=null}}d!=c&&(k=!0);a--}for(l=+!!(f&512)-1;0<a;a--){n=a-1;c=b[n];n-=l;if(!(null==c||H(c,e,n)||ha(c)&&0===c.size))break;var w=!0}if(!k&&!w)return b;b=Array.prototype.slice.call(b,0,
a);d&&b.push(d);return b},xa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ya="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},za=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");
},O=za(this),P=function(a,b){if(b)a:{var c=O;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];if(!(f in c))break a;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&ya(c,a,{configurable:!0,writable:!0,value:b})}},y=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:xa(a)};throw Error("b`"+String(a));},Aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;
return new b},Q;if("function"==typeof Object.setPrototypeOf)Q=Object.setPrototypeOf;else{var R;a:{var Ba={a:!0},Ca={};try{Ca.__proto__=Ba;R=Ca.a;break a}catch(a){}R=!1}Q=R?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("c`"+a);return a}:null}
var Da=Q,Ea=function(a,b){a.prototype=Aa(b.prototype);a.prototype.constructor=a;if(Da)Da(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.K=b.prototype};
P("Promise",function(a){function b(){this.g=null}function c(d){return d instanceof f?d:new f(function(g){g(d)})}if(a)return a;b.prototype.h=function(d){if(null==this.g){this.g=[];var g=this;this.i(function(){g.m()})}this.g.push(d)};var e=O.setTimeout;b.prototype.i=function(d){e(d,0)};b.prototype.m=function(){for(;this.g&&this.g.length;){var d=this.g;this.g=[];for(var g=0;g<d.length;++g){var h=d[g];d[g]=null;try{h()}catch(l){this.l(l)}}}this.g=null};b.prototype.l=function(d){this.i(function(){throw d;
})};var f=function(d){this.h=0;this.i=void 0;this.g=[];this.u=!1;var g=this.l();try{d(g.resolve,g.reject)}catch(h){g.reject(h)}};f.prototype.l=function(){function d(l){return function(m){h||(h=!0,l.call(g,m))}}var g=this,h=!1;return{resolve:d(this.B),reject:d(this.m)}};f.prototype.B=function(d){if(d===this)this.m(new TypeError("d"));else if(d instanceof f)this.D(d);else{a:switch(typeof d){case "object":var g=null!=d;break a;case "function":g=!0;break a;default:g=!1}g?this.A(d):this.s(d)}};f.prototype.A=
function(d){var g=void 0;try{g=d.then}catch(h){this.m(h);return}"function"==typeof g?this.F(g,d):this.s(d)};f.prototype.m=function(d){this.v(2,d)};f.prototype.s=function(d){this.v(1,d)};f.prototype.v=function(d,g){if(0!=this.h)throw Error("e`"+d+"`"+g+"`"+this.h);this.h=d;this.i=g;2===this.h&&this.C();this.H()};f.prototype.C=function(){var d=this;e(function(){if(d.I()){var g=O.console;"undefined"!==typeof g&&g.error(d.i)}},1)};f.prototype.I=function(){if(this.u)return!1;var d=O.CustomEvent,g=O.Event,
h=O.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):"function"===typeof g?d=new g("unhandledrejection",{cancelable:!0}):(d=O.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.i;return h(d)};f.prototype.H=function(){if(null!=this.g){for(var d=0;d<this.g.length;++d)k.h(this.g[d]);this.g=null}};var k=new b;f.prototype.D=function(d){var g=this.l();d.o(g.resolve,g.reject)};
f.prototype.F=function(d,g){var h=this.l();try{d.call(g,h.resolve,h.reject)}catch(l){h.reject(l)}};f.prototype.then=function(d,g){function h(n,w){return"function"==typeof n?function(Y){try{l(n(Y))}catch(Z){m(Z)}}:w}var l,m,D=new f(function(n,w){l=n;m=w});this.o(h(d,l),h(g,m));return D};f.prototype.catch=function(d){return this.then(void 0,d)};f.prototype.o=function(d,g){function h(){switch(l.h){case 1:d(l.i);break;case 2:g(l.i);break;default:throw Error("f`"+l.h);}}var l=this;null==this.g?k.h(h):
this.g.push(h);this.u=!0};f.resolve=c;f.reject=function(d){return new f(function(g,h){h(d)})};f.race=function(d){return new f(function(g,h){for(var l=y(d),m=l.next();!m.done;m=l.next())c(m.value).o(g,h)})};f.all=function(d){var g=y(d),h=g.next();return h.done?c([]):new f(function(l,m){function D(Y){return function(Z){n[Y]=Z;w--;0==w&&l(n)}}var n=[],w=0;do n.push(void 0),w++,c(h.value).o(D(n.length-1),m),h=g.next();while(!h.done)})};return f});P("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});
P("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});P("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});P("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
P("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});P("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});P("Array.prototype.includes",function(a){return a?a:function(b,c){var e=this;e instanceof String&&(e=String(e));var f=e.length;c=c||0;for(0>c&&(c=Math.max(c+f,0));c<f;c++){var k=e[c];if(k===b||Object.is(k,b))return!0}return!1}});
P("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("g`includes");if(b instanceof RegExp)throw new TypeError("h`includes");return-1!==this.indexOf(b,c||0)}});P("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});var r=this||self,Fa=function(a){a:{var b=["WIZ_global_data","oxN3nb"];for(var c=r,e=0;e<b.length;e++)if(c=c[b[e]],null==c){b=null;break a}b=c}a=b&&b[a];return null!=a?a:!1},Ga=r._F_toggles||[];var Ha=!!(Ga[0]&512),Ia=!!(Ga[0]&1024),Ja=!!(Ga[0]&8);var aa=Ha?Ia:Fa(610401301),wa=Ha?Ja:Fa(188588736);var p,Ka=r.navigator;p=Ka?Ka.userAgentData||null:null;var La=u()?!1:t("Trident")||t("MSIE");!t("Android")||v();v();t("Safari")&&(v()||(u()?0:t("Coast"))||(u()?0:t("Opera"))||(u()?0:t("Edge"))||(u()?q("Microsoft Edge"):t("Edg/"))||u()&&q("Opera"));var ra={},L=null;var pa="undefined"!==typeof Uint8Array,qa=!La&&"function"===typeof btoa;var A=0,B=0;var S;S="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0;var Ma=S?function(a,b){a[S]|=b}:function(a,b){void 0!==a.g?a.g|=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})},F=S?function(a){return a[S]|0}:function(a){return a.g|0},M=S?function(a){return a[S]}:function(a){return a.g},G=S?function(a,b){a[S]=b}:function(a,b){void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};var ua={},fa={},Na;Object.freeze(new function(){});Object.freeze(new function(){});var ia=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;var J;var Oa=function(a,b,c){var e=a.j,f=M(e);if(f&2)throw Error();a:{var k=ea(f);if(b>=k){var d=f;if(f&256)var g=e[e.length-1];else{if(null==c)break a;g=e[k+(+!!(f&512)-1)]={};d|=256}g[b]=c;b<k&&(e[b+(+!!(f&512)-1)]=void 0);d!==f&&G(e,d)}else e[b+(+!!(f&512)-1)]=c,f&256&&(c=e[e.length-1],b in c&&delete c[b])}return a},Pa=function(a){var b=void 0===b?0:b;a=a.j;var c=M(a),e=ea(c);1>=e?a=c&256?a[a.length-1][1]:void 0:(c=1+(+!!(c&512)-1),a=0>c||c>=a.length||c>=e?void 0:a[c]);a=null==a?a:ja(a)?"number"===typeof a?
la(a):ma(a):void 0;return null!=a?a:b},Qa=function(a,b,c){if(null!=c){if("number"!==typeof c)throw I("int32");if(!Number.isFinite(c))throw I("int32");c|=0}Oa(a,b,c)};var T=function(a,b,c){this.j=K(a,b,c)};T.prototype.toJSON=function(){return Na?N(this,this.j,!1):N(this,sa(this.j,va,void 0,void 0,!1),!0)};var Ra=function(a){Na=!0;try{return JSON.stringify(a.toJSON(),oa)}finally{Na=!1}};T.prototype.G=ua;T.prototype.toString=function(){return N(this,this.j,!1).toString()};var Sa=function(a){this.j=K(a)};Ea(Sa,T);var Ta=function(a){this.j=K(a,0,"identity.hfcr")};Ea(Ta,T);var Ua=function(a){return function(b){if(null==b||""==b)b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error("n");Ma(b,32);J=b;b=new a(b);J=void 0}return b}}(Ta);var Va=function(a,b,c,e,f){this.m=a;this.i=b;this.l=c;this.h=e;this.g=f};Va.prototype.start=function(){var a=this;if("undefined"!==typeof fetch)if(Wa()){var b=Xa(),c=Date.now();b&&b>c+1E3*this.g&&(b=Date.now()+1E3*this.g,U(b));var e=function(){Ya(a).then(function(){setTimeout(e,1E3*a.g)})};setTimeout(function(){e()},b&&b>c?b-c:0)}else Za(this)};
var Za=function(a){$a(a).then(function(){var b=function(){$a(a).then(function(){setTimeout(b,1E3*a.g)})};setTimeout(function(){b()},1E3*a.g)})},$a=function(a){var b=ab(a);return bb(b).then(function(c){c=cb(Pa(c));c!==a.g&&(a.g=c)}).catch(function(){a.g*=2})},Ya=function(a){var b=Xa();if(!b||Date.now()>=b){var c=Math.floor(1E3*Math.random());return new Promise(function(e){setTimeout(function(){var f=Xa();!f||Date.now()>=f?e(db(a)):e()},c)})}return Promise.resolve()},bb=function(a){a={method:"POST",
credentials:"same-origin",cache:"no-store",mode:"same-origin",headers:{"Content-Type":"application/json"},body:Ra(a)};if("undefined"!==typeof AbortController){var b=new AbortController;setTimeout(function(){b.abort()},3E4);a.signal=b.signal}return fetch(new Request("/RotateCookies",a)).then(function(c){return c.text()}).then(function(c){return Ua(JSON.stringify(JSON.parse(c.substring(5))[0]))})},ab=function(a){var b=new Sa;var c=a.m;if(null!=c){var e=!!e;if(!ja(c))throw I("int64");"string"===typeof c?
c=ma(c):e?(c=Math.trunc(c),Number.isSafeInteger(c)?c=String(c):(e=String(c),ka(e)?c=e:(C(c),c=da()))):c=la(c)}b=Oa(b,2,c);0!==a.i&&Qa(b,1,a.i);0!==a.l&&Qa(b,3,a.l);0!==a.h&&Qa(b,4,a.h);return b},db=function(a){U(Date.now()+1E3*a.g);var b=ab(a);return bb(b).then(function(c){c=cb(Pa(c));c!==a.g&&(U(Date.now()+1E3*c),a.g=c)}).catch(function(){a.g*=2;U(Date.now()+1E3*a.g)})},Wa=function(){try{var a=window.localStorage;if(!a)return!1;a.setItem("cookieRotationStorageAccessTest","1");a.removeItem("cookieRotationStorageAccessTest");
return!0}catch(b){return!1}},cb=function(a){60>a&&(a=60);return a},Xa=function(){try{var a=window.localStorage.getItem("nextRotationAttemptTs");if(!a)return null;var b=Math.floor(Number(a));return Number.isNaN(b)?null:b}catch(c){return null}},U=function(a){try{window.localStorage.setItem("nextRotationAttemptTs",a.toString())}catch(b){}};var eb=function(a,b,c,e,f){(new Va(a,b,c,e,f)).start()},V=["init"],W=r;V[0]in W||"undefined"==typeof W.execScript||W.execScript("var "+V[0]);for(var X;V.length&&(X=V.shift());)V.length||void 0===eb?W[X]&&W[X]!==Object.prototype[X]?W=W[X]:W=W[X]={}:W[X]=eb;
}catch(e){_._DumpException(e)}
}).call(this,this.default_IdentityRotateCookiesHttp);
// Google Inc.
